<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

1. Compute the scaler product of two vectors

> In mathematics, the dot product or scalar product is an algebraic operation that takes two equal-length sequences of numbers (usually coordinate vectors) and returns a single number. 

> we can calculate it this way:

        a · b = ax × bx + ay × by
        
Hint: [Dot Product](https://www.mathsisfun.com/algebra/vectors-dot-product.html)

In [9]:
import numpy as np

In [10]:
a = [-12, 16]
b = [12, 9]
np.dot(a, b)  #12*(-12) + 16*9

0

2. Compute the cross product of two vectors

> When a and b start at the origin point (0,0,0), the Cross Product will end at:

        cx = aybz − azby
        cy = azbx − axbz
        cz = axby − aybx
        
Hint: [Cross Product](https://www.mathsisfun.com/algebra/vectors-cross-product.html)

In [11]:
x = np.array([[1,2,3], [4,5,6]])  #this is not vector, it is matrix
y = np.array([[4,5,6], [1,2,3]])
np.cross(x, y)

array([[-3,  6, -3],
       [ 3, -6,  3]])

3. Compute the Hademard product (entry-wise multiplication) of two vectors.

> In mathematics, the Hadamard product (also known as the Schur product[1] or the entrywise product[2]:ch. 5) is a binary operation that takes two matrices of the same dimensions and produces another matrix of the same dimension as the operands where each element i, j is the product of elements i, j of the original two matrices. It should not be confused with the more common matrix product. It is attributed to, and named after, either French mathematician Jacques Hadamard or German mathematician Issai Schur. [Wiki](https://en.wikipedia.org/wiki/Hadamard_product_(matrices))

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/4eb9bb54b2820fb3583901ec05bc4b474b6d90bc)

In [12]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
np.multiply(a,b)

array([[ 5, 12],
       [21, 32]])

4. Compute the sum of two matrices.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/0fb7845af355c550d44020e52699069c044126a9)

In [13]:
# Program to add two matrices using nested loop

X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[5,8,1],
    [6,7,3],
    [4,5,9]]

result = [[0,0,0],   #first step
         [0,0,0],
         [0,0,0]]

#iterate through rows
for i in range (len(X)):
    #iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]  #i, j = 0,1,2 (index no)
for r in result: 
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


In [15]:
#program to add two matrices using list comprehension 

result = [[X[i][j] + Y[i][j] for j in range (len(X[0]))] for i in range(len(X))]

print(result)

[[17, 15, 4], [10, 12, 9], [11, 13, 18]]


In [16]:
result = [[X[i][j] + Y[i][j] for j in range (len(X[0]))] for i in range(len(X))]

for r in result:
    print(r)

[17, 15, 4]
[10, 12, 9]
[11, 13, 18]


5. Compute the product of two matrices.

![](https://upload.wikimedia.org/wikipedia/commons/e/eb/Matrix_multiplication_diagram_2.svg)

In [18]:
# Program to multiply two matrices using nested loops  - # any real life examples?????

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

#iterate through rows of X
for i in range (len(X)):
    #iterate through columns of Y
    for j in range(len(Y[0])):
        #iterate through rows of Y
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]
    
for r in result:
    print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


6. Compute the determinant of an n x n matrix.

![](https://integratedmlai.com/wp-content/uploads/2018/12/Matrix_Det_2x2.png)

Hint: [Find the Determinant of a Matrix with Pure Python without Numpy or Scipy](https://integratedmlai.com/find-the-determinant-of-a-matrix-with-pure-python-without-numpy-or-scipy/)

Hint: Use 
> np.linalg.det

In [ ]:
# https://www.mathsisfun.com/algebra/matrix-determinant.html

In [19]:
matrix = [[-2,2,-3],[-1,1,3],[2,0,-1]]
det = np.linalg.det(matrix) 
print(det)

17.999999999999996


7. Compute the inverse of an n x n matrix.

For a 3×3 matrix

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation3.gif)

the matrix inverse is

![](http://mathworld.wolfram.com/images/equations/MatrixInverse/NumberedEquation4.gif)

Hint: Use 
> from numpy.linalg import inv

In [20]:
from numpy.linalg import inv
a = np.array([[1., 2.], [3., 4.]])
ainv= inv(a)

In [21]:
ainv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



