<div>
<img src=https://www.institutedata.com/wp-content/uploads/2019/10/iod_h_tp_primary_c.svg width="300">
</div>

# Lab 4.1.2 Linear Regression

## Prediction of House Price Using Linear Regression

### Data

The Sacramento real estate transactions file is a list of 985 real estate transactions in the Sacramento area reported over a five-day period, as reported by the Sacramento Bee.

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

from scipy import stats
from matplotlib import pyplot as plt

%matplotlib inline

### 1. Explore Data

Perform EDA on this dataset. Find Dependent and Independent Variables to predict house price.

In [3]:
# Read CSV
data = pd.read_csv("C:/Users/victo/Documents/Institute_of_Data/DATA/Sacramento_transactions.csv")

In [4]:
data.shape

(985, 12)

### 2. Predict Price

We are going to predict `price` from available information.

#### 2.1 What is the Target Variable? Why?

In [31]:
# ANSWER

all same as lab 4.1.1

#### 2.2 List all possible variables which might be Independent/Predictor variable.

In [32]:
# ANSWER

all same as lab 4.1.1

#### 2.3 Find correlation between variables

Find correlation between variables. Which is the best predictor? Why? State your reason.

In [33]:
# ANSWER

all same as lab 4.1.1

#### 2.4 Find Coefficient and Intercept using Linear Regression

Using LinearRegression of sklearn.linear_model package find Coefficient and Intercept.

Create an instance of LinearRegression.

Explore following methods:

- fit
- predict
- score

In [5]:
from sklearn.linear_model import LinearRegression

##### 2.4.1 Fit predictor and target variables using linear regression 

In [ ]:
# y = linreg.intercept_ + linreg.coef_ * x

In [6]:
# ANSWER

X = data['sq__ft'].values.reshape(-1,1)   
Y = data['price']

linreg = LinearRegression()
linreg.fit(X, Y)

print(linreg.coef_, linreg.intercept_)

[54.15863969] 162930.16140699777


In [8]:
data['sq__ft'].shape

(985,)

In [10]:
data['sq__ft'].values.reshape(-1,1)  
#to change from 1D array to 2D array, but dont need to change Y axis, only X axis

array([[ 836],
       [1167],
       [ 796],
       [ 852],
       [ 797],
       [1122],
       [1104],
       [1177],
       [ 941],
       [1146],
       [ 909],
       [1289],
       [ 871],
       [1020],
       [1022],
       [1134],
       [ 844],
       [ 795],
       [ 588],
       [1356],
       [1118],
       [1329],
       [1240],
       [1601],
       [ 901],
       [1088],
       [ 963],
       [1119],
       [1380],
       [1248],
       [1039],
       [1152],
       [1380],
       [1116],
       [1039],
       [1418],
       [1082],
       [1472],
       [1146],
       [ 760],
       [1304],
       [1207],
       [1056],
       [1043],
       [1587],
       [1120],
       [1580],
       [1955],
       [1656],
       [1477],
       [1188],
       [1590],
       [1463],
       [1714],
       [1185],
       [1406],
       [1943],
       [1172],
       [1152],
       [1851],
       [1215],
       [1130],
       [1603],
       [1479],
       [1420],
       [1280],
       [15

In [11]:
data['sq__ft'].values.reshape(-1,1).shape

(985, 1)

##### 2.4.2 Find R Score

The coefficient R^2 is defined as (1 - u/v), where u is the residual sum of squares ((y_true - y_pred) ** 2).sum() and v is the total sum of squares ((y_true - y_true.mean()) ** 2).sum(). 

The best possible score is 1.0 and it can be negative (because the
model can be arbitrarily worse).

Find $R^2$ Using ```score``` method of Linear Regression.

In [7]:
# ANSWER

linreg.score(X, Y)

0.11148717682951437

In [13]:
#example:
    
x = 2000 #find predicted y 'price'

In [14]:
x = np.array(2000).reshape(-1,1)

In [15]:
#1. first way of predicting y
linreg.predict(x)

array([271247.44078406])

In [16]:
#2. second way of predicting y 'price'
y = linreg.intercept_ + linreg.coef_ * x
x = 2000

y

array([[271247.44078406]])

### 3. Splitting Data

In [17]:
from sklearn.model_selection import train_test_split

#### 3.1 Create training and testing subsets

Hint: Using `train_test_split` Library.

```
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
```

In [38]:
# ANSWER
## Create training and testing subsets

#### 3.2 Check Shape, Sample of Test Train Data

In [39]:
# ANSWER
## Check training/test data

#### 3.3 Using Linear Regression Find The Score

1. Fit model using X_train, y_train
2. Find score using X_test, y_test

In [40]:
# ANSWER

In [41]:
# ANSWER

### 4. Predict House Price

Let's assume we have information of following house:

- street:	1140 EDMONTON DR
- city:	SACRAMENTO
- zip:	95833
- state:	CA
- beds:	3
- baths:	2
- sq__ft:	1204
- type:	Residential

**Predict the price of this house using linear regression model.**

In [42]:
# ANSWER

#### Find the error

In [ ]:
# Predict price from X_test



---



---



> > > > > > > > > © 2021 Institute of Data


---



---



